name: Build and publish to Docker hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run tests  
      run: npm run test
      
    - name: Build the Docker image
      run: docker build . --tag clemensn/software-deployment-ue5:dev

    - name: Push image to Docker hub
      run: |
        docker login -u clemensn -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push clemensn/software-deployment-ue5:dev
