name: Release Build and Deploy to Docker Hub

on:
  pull_request:
    branches: 
      - 'release/*'
  workflow_dispatch:

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Node.js tests
      run: |
        npm install
        npm test

    - name: Build the Docker image
      run: docker build . --tag clemensn/software-deployment-ue5:latest

    - name: Push image to Docker hub
      run: |
        docker login -u clemensn -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push clemensn/software-deployment-ue5:latest

