# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, test and deploy to Release

on:
  pull_request:
    branches:
      release
    types:
      closed
  workflow_dispatch:

jobs:

  test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Run Node.js tests
      run: |
        npm install
        npm test

  build:
    runs-on: 'ubuntu-latest'
    needs: test

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c340ca7cb5284fe7b751ceb2682734a9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_05325f835d474d7c969aaa5d4586678c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/clemensn/software-deployment-ue5:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Uebung5WebApp2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0afd85f3e66e4c588935088ff4137713 }}
        images: 'index.docker.io/clemensn/software-deployment-ue5:latest'